### ISSUE TITLE
FFS client crash - Forge 1.9 build 180*

### ISSUE THREAD

**Issue by ShadowDrakken** [Lordmau5/FFS-v1.X#44]
**FancyFluidStorage Version**:
1.4.5.8

**MinecraftForge Version**:
1.9-12.16.0.180*

**Client or Server?**:
- [X] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraftforge.common.config.Property.comment from class com.lordmau5.ffs.FancyFluidStorage
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:172)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:240)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:434)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraftforge.common.config.Property.comment from class com.lordmau5.ffs.FancyFluidStorage
    at com.lordmau5.ffs.FancyFluidStorage.loadConfig(FancyFluidStorage.java:87)
    at com.lordmau5.ffs.FancyFluidStorage.preInit(FancyFluidStorage.java:137)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**What happens / happened?**:
Crashes during Forge loading screen

**How can we reproduce it?**:
Launch the game

**Comment by Lordmau5** [comment]
Should be resolved in 1.5.1, since we build against Forge 1808 now.
