### ISSUE TITLE
1.9.4-1.5.3.11 crashes dedicated forge server 1.9.4 build 1937 on startup

### ISSUE THREAD

**Issue by kreezxil** [Lordmau5/FFS-v1.X#55]
Happy Face (You see me smiling from ear to ear)

**FancyFluidStorage Version**:
1.9.4-1.5.3.11 

**MinecraftForge Version**:
1.9.4-12.17.0.1937

**Client or Server?**:
- [ ] Client
- [x] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
https://gist.github.com/29d025e419f4f0127eb94db10fba3d8a

**What happens / happened?**:
Server crashes on startup

**How can we reproduce it?**:
Start dedicated server using Forge 1.9.4-12.17.0.1937

fml server latest:
https://gist.github.com/fff1d598ab04978abdeae38656adc1cd

**Comment by Lordmau5** [comment]
Are all the mods you are running working on that version of Forge?

The version I've built against is 12.17.0.1909 and it works on that one.
I can build against a newer version with the chance of potentially breaking modpacks...

**Comment by Lordmau5** [comment]
Just updated it temporarily to the newest build - it's not crashing.

I'm sorry to say, but I'm 99% sure it's one of the other mods causing this.

---

Try an empty instance with just Forge + FFS and try to reproduce it.

If it doesn't happen, add single mods one-by-one up until it does crash.

**Comment by kreezxil** [comment]
Yes, they are all running on that version of forge.

-----Original Message-----

**Comment by Lordmau5** [comment]
As I've already suggested, please try the newest version (In this case, 1.5.5-b15) **alone** in an instance.

Then just adds mods in bulk (3-4 at a time or so) and see if one of them crashes in combination.

A friend of me also has a modpack with it and a bunch of mods and he **can't** reproduce this crash at all.

**Comment by maxpowa** [comment]
@Lordmau5 ~~have you tested this at all on a dedicated server?~~

~~I could definitely see this happening because FFSStateProps imports client classes when it imports PropertyModel. Should put a @SideOnly(CLIENT) annotation on the model properties (https://github.com/Lordmau5/FFS/blob/master/src/main/java/com/lordmau5/ffs/util/FFSStateProps.java#L14) in FFSStateProps.~~

~~Better solution would be to have two FFSStateProps classes, one that's client and one that's server, where the Client one extends the server's.~~

Confirmed to be working fine on dedicated server with just FFS.

**Comment by Lordmau5** [comment]
Hmm, good point... I'll get to that in a few

**Comment by Lordmau5** [comment]
@kreezxil Just noticed that the fml-server-latest.log is cut off after line 8382?
Could you upload the full log to some host (Dropbox, whatever)? :P

**Comment by kreezxil** [comment]
At the top of the gist page there is a link to the full file.

-----Original Message-----

**Comment by Lordmau5** [comment]
`[17:06:30] [Server thread/ERROR] [FML/]: Caught exception from actuallyadditions
java.lang.NoSuchMethodError: de.ellpeck.actuallyadditions.mod.proxy.IProxy.addRenderRegister(Lnet/minecraft/item/ItemStack;Lnet/minecraft/client/renderer/block/model/ModelResourceLocation;)V
    at de.ellpeck.actuallyadditions.mod.blocks.base.BlockContainerBase.registerRendering(BlockContainerBase.java:77) ~[BlockContainerBase.class:?]
    at de.ellpeck.actuallyadditions.mod.blocks.base.BlockContainerBase.register(BlockContainerBase.java:61) ~[BlockContainerBase.class:?]
    at de.ellpeck.actuallyadditions.mod.blocks.base.BlockContainerBase.<init>(BlockContainerBase.java:55) ~[BlockContainerBase.class:?]
    at de.ellpeck.actuallyadditions.mod.blocks.BlockBookletStand.<init>(BlockBookletStand.java:59) ~[BlockBookletStand.class:?]
    at de.ellpeck.actuallyadditions.mod.blocks.InitBlocks.init(InitBlocks.java:123) ~[InitBlocks.class:?]
    at de.ellpeck.actuallyadditions.mod.ActuallyAdditions.preInit(ActuallyAdditions.java:81) ~[ActuallyAdditions.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:566) ~[uno-niner-four.jar:?]
    at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.9.4.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228) ~[uno-niner-four.jar:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206) ~[uno-niner-four.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.9.4.jar:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) [LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:587) [Loader.class:?]
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:93) [FMLServerHandler.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320) [FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:118) [lb.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]`

Can you try it without "actuallyadditions", please?
I'm curious.

**Comment by maxpowa** [comment]
We're pretty sure this is caused by Farseek at this point.

**Comment by kreezxil** [comment]
Thanks that is very helpful.

-----Original Message-----

**Comment by kreezxil** [comment]
I updated to build 1954 of forge today and got the error back, disregard if the dev hasn't been made public yet or not, your choice. :)

Issue:  fancy-fluid-storage-1.9.4-1.6.0-b19 crashes dedicated Forge 1.9.4 build 1954 on startup 

https://gist.github.com/51f0547d87b7a65e8ed5afe56e9cd911

https://gist.github.com/93e9572d1436b6c6493f0039e7cc1237

**Comment by Lordmau5** [comment]
Yea, but it's not on our side.
I don't want to be a dick, but I would really love if you could forward the issue to the Farseek developer.
Moan at him, it's not our mod that causes this.

https://github.com/delvr/Farseek/issues/10

**Comment by canitzp** [comment]
This is cause because at the server there are no net.minecraft.client packages and you try to use these packages

**Comment by Lordmau5** [comment]
No we are not, Farseek is messing with bullshit in the IBakedModel interface and we aren't at fault for this.
